import type { NextPage, NextPageContext } from 'next';
import { useState } from 'react';
import Head from 'next/head';
import { getSession } from 'next-auth/react';

const Home: NextPage = ({ session }: any) => {
  const [projectsListOpen, setProjectsListOpen] = useState(true);

  return (
    <>
      <Head>
        <title>Ilytodo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export async function getServerSideProps(ctx: NextPageContext) {
  const session = await getSession(ctx);

  return {
    props: {
      session,
    },
  };
}

export default Home;
